import type { Metadata } from "next";
import Link from "next/link";
import { listEvents, listEvidenceForEvents } from "@bai/db";
import type { EventEvidenceItem } from "@bai/domain";
import {
  Badge,
  Button,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@bai/ui";
import { loadTenancyContext } from "@/lib/tenancy";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { formatDate } from "@/lib/format";
import { PageHeader, EmptyState } from "../_components/page-parts";
import { EvidenceSheet } from "../_components/evidence-sheet";

export const metadata: Metadata = { title: "Events" };

const EVENT_TYPE_OPTIONS = [
  "listing_created",
  "price_changed",
  "rating_changed",
  "review_count_changed",
  "host_changed",
  "direct_channel_added",
] as const;

function humanize(value: string): string {
  return value.replace(/_/g, " ").replace(/^\w/, (c) => c.toUpperCase());
}

type SearchParams = Promise<{ type?: string; cursor?: string }>;

export default async function EventsPage({
  searchParams,
}: {
  searchParams: SearchParams;
}) {
  const params = await searchParams;
  const ctx = await loadTenancyContext();
  const dataset = ctx?.selectedDataset ?? null;

  if (!dataset) {
    return (
      <div>
        <PageHeader title="Events" />
        <EmptyState
          title="No dataset selected"
          description="Select a dataset to view its events."
        />
      </div>
    );
  }

  const supabase = await createSupabaseServerClient();
  const page = await listEvents(supabase, dataset.id, {
    filters: { eventType: params.type || undefined },
    page: { cursor: params.cursor },
  });

  const evidence = await listEvidenceForEvents(
    supabase,
    page.items.map((event) => event.id),
  );
  const evidenceByEvent = new Map<string, EventEvidenceItem[]>();
  for (const item of evidence) {
    const list = evidenceByEvent.get(item.eventId) ?? [];
    list.push(item);
    evidenceByEvent.set(item.eventId, list);
  }

  const baseQuery: Record<string, string> = {};
  if (params.type) baseQuery.type = params.type;

  return (
    <div>
      <PageHeader
        title="Events"
        description={`Evidence-backed observations in ${dataset.name}. Observation language only.`}
      />

      <form
        method="get"
        className="mb-4 flex flex-wrap items-end gap-3"
        aria-label="Filter events"
      >
        <label className="flex flex-col gap-1 text-sm">
          <span className="font-medium">Type</span>
          <select
            name="type"
            defaultValue={params.type ?? ""}
            className="h-9 rounded-md border border-input bg-background px-2 text-sm"
          >
            <option value="">All types</option>
            {EVENT_TYPE_OPTIONS.map((type) => (
              <option key={type} value={type}>
                {humanize(type)}
              </option>
            ))}
          </select>
        </label>
        <Button type="submit" size="sm" variant="outline">
          Apply
        </Button>
        {params.type ? (
          <Button asChild size="sm" variant="ghost">
            <Link href="/app/events">Clear</Link>
          </Button>
        ) : null}
      </form>

      {page.items.length === 0 ? (
        <EmptyState
          title="No events"
          description="No events match the current filter. Events are generated by the snapshot/diff and lifecycle engines from Milestone 4."
        />
      ) : (
        <>
          <div className="rounded-lg border border-border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Event</TableHead>
                  <TableHead>When</TableHead>
                  <TableHead>Confidence</TableHead>
                  <TableHead className="text-right">Evidence</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {page.items.map((event) => (
                  <TableRow key={event.id}>
                    <TableCell>
                      <div className="flex flex-col gap-1">
                        <Badge variant="secondary" className="w-fit">
                          {humanize(event.eventType)}
                        </Badge>
                        <span className="font-medium">{event.title}</span>
                        {event.summary ? (
                          <span className="text-sm text-muted-foreground">
                            {event.summary}
                          </span>
                        ) : null}
                      </div>
                    </TableCell>
                    <TableCell>{formatDate(event.eventAt)}</TableCell>
                    <TableCell>
                      {event.confidence ? (
                        <Badge variant="outline">{event.confidence}</Badge>
                      ) : (
                        "—"
                      )}
                    </TableCell>
                    <TableCell className="text-right">
                      <EvidenceSheet
                        eventTitle={event.title}
                        evidence={evidenceByEvent.get(event.id) ?? []}
                      />
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>

          <div className="mt-4 flex items-center justify-end gap-2">
            {page.nextCursor ? (
              <Button asChild size="sm" variant="outline">
                <Link
                  href={{
                    pathname: "/app/events",
                    query: { ...baseQuery, cursor: page.nextCursor },
                  }}
                >
                  Next page
                </Link>
              </Button>
            ) : (
              <span className="text-sm text-muted-foreground">
                End of results
              </span>
            )}
          </div>
        </>
      )}
    </div>
  );
}
